services:
  records:
    image: "gcr.hrz.tu-chemnitz.de/praktikum-scc/ws23-gruppe1/gruppe1/records:v1.f.a.0"
    volumes:
      - /db/records.db:/app/db
    ports:
      - "8000:8000"
    environment:
      - JWT_TOKEN=iqEHyCjfqRRrI2ctKFxgjfqzIqfobKgt
  user:
    build: ./services/user/
    image: "gcr.hrz.tu-chemnitz.de/praktikum-scc/ws23-gruppe1/gruppe1/user:0.0.2"
    volumes:
      - ./db/:/db
    ports:
      - "9001:9001"
    environment:
      - RODEIT_SECRET=iqEHyCjfqRRrI2ctKFxgjfqzIqfobKgt
      - DATABASE_URL=sqlite://test.db
  bucket_list:
    build: ./services/bucket_list/
    image: "gcr.hrz.tu-chemnitz.de/praktikum-scc/ws23-gruppe1/gruppe1/bucket_list:0.2.0"
    ports:
      - "3000:3000"
    environment:
      - RODEIT_SECRET=iqEHyCjfqRRrI2ctKFxgjfqzIqfobKgt
