---

openapi: 3.0.0
info:
  title: "Record API"
  version: "1.0.1"

servers:
  - url: "/"

components:
  schemas:
    Record:
      type: "object"
      required:
        - user_id
        - rollercoaster_id
      properties:
        user_id:
          type: "integer"
        rollercoaster_id:
          type: "integer"
  parameters:
    record_id:
      name: "record_id"
      in: path
      required: True
      schema:
        type: "integer"
    user_id:
      name: "user_id"
      in: path
      required: True
      schema:
        type: "integer"
    rollercoaster_id:
      name: "rollercoaster_id"
      in: path
      required: True
      schema:
        type: "integer"
paths:
  "/":
    get:
      operationId: "record.main"
      responses:
        "200":
          description: ""
  /getAll:
    get:
      operationId: "record.get_all"
      responses:
        "200":
          description: "Delete me"
  /record/id/{record_id}:
    get:
      operationId: "record.get_by_id"
      parameters:
        - $ref: "#/components/parameters/record_id"
      responses:
        "200":
          description: ""
        "404":
          description: "not found"
  /user/{user_id}:
    get:
      operationId: "record.get"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "200":
          description: ""
        "404":
          description: "not found"
  /record:
    post:
      operationId: "record.submit"
      requestBody:
          description: ""
          required: True
          content:
            application/json:
              schema:
                x-body-name: "record"
                $ref: "#/components/schemas/Record"
      responses:
        "201":
          description: ""
  /rollercoaster/{rollercoaster_id}:
    get:
      operationId: "record.get_by_rollercoaster"
      parameters:
        - $ref: "#/components/parameters/rollercoaster_id"
      responses:
        "200":
          description: ""
        "404":
          description: "not found"
