/*
 * Captain Coaster API
 *
 * Welcome to Captain Coaster API! API Keys for authentication can be found in your profile page. Contact us to get support.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoasterListCoaster : Coaster



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoasterListCoaster {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "park", skip_serializing_if = "Option::is_none")]
    pub park: Option<Box<crate::models::ParkListCoaster>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::StatusListCoaster>>,
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<i32>,
}

impl CoasterListCoaster {
    /// Coaster
    pub fn new(name: String) -> CoasterListCoaster {
        CoasterListCoaster {
            id: None,
            name,
            park: None,
            status: None,
            rank: None,
        }
    }
}


