/*
 * Captain Coaster API
 *
 * Welcome to Captain Coaster API! API Keys for authentication can be found in your profile page. Contact us to get support.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ImageReadImage : Badge



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageReadImage {
    #[serde(rename = "coaster", skip_serializing_if = "Option::is_none")]
    pub coaster: Option<String>,
    #[serde(rename = "credit")]
    pub credit: String,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

impl ImageReadImage {
    /// Badge
    pub fn new(credit: String) -> ImageReadImage {
        ImageReadImage {
            coaster: None,
            credit,
            path: None,
        }
    }
}


