/*
 * Captain Coaster API
 *
 * Welcome to Captain Coaster API! API Keys for authentication can be found in your profile page. Contact us to get support.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// StatusReadStatus : Status



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusReadStatus {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isRateable", skip_serializing_if = "Option::is_none")]
    pub is_rateable: Option<bool>,
}

impl StatusReadStatus {
    /// Status
    pub fn new() -> StatusReadStatus {
        StatusReadStatus {
            id: None,
            name: None,
            is_rateable: None,
        }
    }
}


