[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aide = { version = "0.13.2", features = ["macros"] }
axum = "0.7.4"
jsonwebtoken = "9.2.0"
serde = "1.0.195"
