import { OpenAPIV3_1 } from 'openapi-types';
import { merge } from 'ts-deepmerge';

export type Spec = {
	name: string;
	route: string;
	spec: OpenAPIV3_1.Document;
};

const OPERATIONS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'] as const;

export function merge_specs(root: OpenAPIV3_1.Document, specs: Spec[]): OpenAPIV3_1.Document {
	let rebased_specs = specs.map(({ name, route, spec }) => ({
		...spec,
		paths: Object.fromEntries(
			Object.entries(spec.paths!).map(([path, item]) => {
				OPERATIONS.forEach((op) => {
					const operation = item![op];
					if (!operation) return;
					if (operation.tags !== undefined) {
						// remove the 'crate' tag generated by utoipa
						operation.tags = operation.tags.filter((tag) => tag !== 'crate');
						operation.tags.push(name);
					} else {
						operation.tags = [name];
					}
				});
				return [`${route}${path}`, item];
			})
		),
	}));
	return merge(...rebased_specs, root) as unknown as OpenAPIV3_1.Document;
}

