---

openapi: 3.0.0
info:
  title: "Credit API"
  version: "1.0.1"

servers:
  - url: "/"

components:
  parameters:
    credit_id:
      name: "credit_id"
      in: path
      required: True
      schema:
        type: "integer"
    user_id:
      name: "user_id"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  "/":
    get:
      operationId: "credit.main"
      responses:
        "200":
          description: ""
  /getAll:
    get:
      operationId: "credit.get_all"
      responses:
        "200":
          description: ""
  /getById/{credit_id}:
    get:
      operationId: "credit.get_by_id"
      parameters:
        - $ref: "#/components/parameters/credit_id"
      responses:
        "200":
          description: ""
        "404":
          description: "not found"
  /get/{user_id}:
    get:
      operationId: "credit.get"
      parameters:
        - $ref: "#/components/parameters/user_id"
      responses:
        "200":
          description: ""
        "404":
          description: "not found"